sequenceDiagram
    autonumber

    actor U as User
    participant NS as Note Service
    participant AS as Authorization Service
    participant MB as Message Broker
    participant SW as Search Worker
    participant SS as Search Service

    U->>+NS: CreateNote
    NS->>+AS: HasWorkspacePermission
    break Authorization Failed
        AS-->>NS: No Permission
        NS-->>U: No Permission
    end
    AS-->>-NS: Ok
    NS->>NS: Create Note
    par Response
        NS-->>-U: Note ID
    and NoteCreated event
        loop NoteCreatedEvent not published
            NS-)MB: Publish NoteCreatedEvent
        end
        MB-)SW: Retrieve NoteCreatedEvent
        SW->>SW: Process NoteCreatedEvent
        SW->>+SS: Index Note info
        SS->>+SS: Index Note
    end
