sequenceDiagram
    autonumber

    actor U as User
    participant NS as Note Service
    participant AS as Authorization Service
    participant MB as Message Broker
    participant SW as Search Worker
    participant SS as Search Service
    actor SU as Subcribed Users

    U->>+NS: CreateNote
    NS->>+AS: HasWorkspacePermission
    break Authorization Failed
        AS-->>NS: No Permission
        NS-->>U: No Permission
    end
    AS-->>-NS: Ok
    NS->>NS: Create Note
    par Response
        NS-->>U: Note ID
    and NoteCreated domain event
        loop Domain NoteCreatedEvent not published
            NS-)-MB: Publish domain NoteCreatedEvent
        end
        MB-)+NS: Domain NoteCreatedEvent
        par Publish workspace event
            loop Not processed domain NoteCreatedEvent
                NS->>NS: Convert to workspace NoteCreatedEvent
            end
            NS-)SU: Publish workspace NoteCreatedEvent
        and Publish NoteCreatedEvent integration event
            loop Not processed domain NoteCreatedEvent
                NS->>NS: Convert to NoteCreatedEvent
            end
            NS-)-MB: Publish integration NoteCreatedEvent
            MB-)+SW: Retrieve integration NoteCreatedEvent
            SW->>SW: Process NoteCreatedEvent
            SW->>+SS: Index Note
            par Ack
                SS-->>-SW: Ok
            and Indexing Note
                SS->>+SS: Index Note
            end
        end
    end
