sequenceDiagram
    autonumber

    actor U as User
    participant NS as Note Service
    participant DS as Document Service
    participant AS as Authorization Service
    actor SU as Subcribed Users

    U->>+NS: GetNote
    NS->>NS: Get Note
    NS->>+AS: HasNotePermission
    break Authorization Failed
        AS-->>NS: No Permission
        NS-->>U: No Permission
    end
    AS-->>-NS: Ok
    NS-->>-U: Note
    U->>+DS: Hocuspocus Connection
    DS->>DS: Get Document
    alt Document does not exists
        DS->>+NS: CheckNoteExistence
        NS->>NS: Check Note existence
        alt Note does not exists
            NS-->>-DS: Not found
            DS-->>U: Not found
        else Note exists
            DS->>DS: Init document
        end
    end
    DS-->>U: Hocuspocus Connection
    loop Edit debounce by handled by Hocuspocus
        U->>DS: Edit Document
        DS->>DS: Save Document changes
        DS-->>SU: Broadcast Document changes
    end
