name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: typst-community/setup-typst@v5
        with:
          cache-dependency-path: requirements.typ

      - name: Setup Mise
        uses: jdx/mise-action@v4
        with:
          experimental: true

      - name: Build
        run: just build

      - name: Upload Artifact PDF
        uses: actions/upload-artifact@v7
        with:
          name: pdf
          path: build/DA1_23520161_TranNguyenThaiBinh_23521049_NguyenThaiGiaNguyen_SE121.Q21.pdf
          archive: false

      - name: Upload Artifact HTML
        uses: actions/upload-artifact@v7
        with:
          name: html
          path: build/index.html
          archive: false

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
